// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIH1QrpfAsAaM3eIGT8Izh-fAyRFGbWeU',
    appId: '1:499428402262:web:91b1b065253fd9b390c7f7',
    messagingSenderId: '499428402262',
    projectId: 'petfaves-b8751',
    authDomain: 'petfaves-b8751.firebaseapp.com',
    storageBucket: 'petfaves-b8751.appspot.com',
    measurementId: 'G-P3M6PDBK4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm-uwGBVBnQNwmqMnjWb8aCbXp229KoC8',
    appId: '1:499428402262:android:6879d9658822477090c7f7',
    messagingSenderId: '499428402262',
    projectId: 'petfaves-b8751',
    storageBucket: 'petfaves-b8751.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG-Vf2LDhVXfPVpK7jv4nUdQ81aRke9Q4',
    appId: '1:499428402262:ios:420b20a8e054f64f90c7f7',
    messagingSenderId: '499428402262',
    projectId: 'petfaves-b8751',
    storageBucket: 'petfaves-b8751.appspot.com',
    androidClientId: '499428402262-a42bejovvu7jcu5atvue3ia6s52jio21.apps.googleusercontent.com',
    iosClientId: '499428402262-jaao7v5b6pa8elm7r947f5o6gtlqu9et.apps.googleusercontent.com',
    iosBundleId: 'com.example.petfaves',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG-Vf2LDhVXfPVpK7jv4nUdQ81aRke9Q4',
    appId: '1:499428402262:ios:775bd0a05c3673f090c7f7',
    messagingSenderId: '499428402262',
    projectId: 'petfaves-b8751',
    storageBucket: 'petfaves-b8751.appspot.com',
    androidClientId: '499428402262-a42bejovvu7jcu5atvue3ia6s52jio21.apps.googleusercontent.com',
    iosClientId: '499428402262-45pis74eoddlfmjg5a13cu76bpdi8pip.apps.googleusercontent.com',
    iosBundleId: 'com.example.petfaves.RunnerTests',
  );
}
